/** Same observable-state capture pipeline for references and builds. Node 22+. No fidelity claims. */
import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
export const VIEWPORTS={desktop:{width:1440,height:900},tablet:{width:1024,height:768},phone:{width:390,height:844}};
const slug=(s)=>s.replace(/[^a-z0-9_-]/gi,'-').slice(0,100);
async function snapshot(page){return page.evaluate(()=>{
 const key=e=>{if(e.id)return '#'+CSS.escape(e.id);let a=[],n=e;for(let i=0;n&&i<9;i++,n=n.parentElement){let j=1,p=n;while(p=p.previousElementSibling)j++;a.unshift(n.tagName.toLowerCase()+`:nth-child(${j})`);}return a.join('>')};
 const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,top:r.top+scrollY,width:r.width,height:r.height}};
 const all=[...document.querySelectorAll('body *')].filter(e=>!['SCRIPT','STYLE','LINK','META','NOSCRIPT'].includes(e.tagName));
 const motion=all.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&(r.bottom>=-innerHeight&&r.top<=innerHeight*2)}).slice(0,2500).map(e=>{const s=getComputedStyle(e);return {key:key(e),...rect(e),position:s.position,stickyTop:s.top,transform:s.transform,opacity:s.opacity,filter:s.filter,clipPath:s.clipPath,color:s.color}});
 let root=document.querySelector('main')||document.querySelector('[role=main]')||document.querySelector('#main')||document.body;
 while(root.children.length===1&&root.firstElementChild?.children.length>1)root=root.firstElementChild;
 let blocks=[...root.children].filter(e=>e.getBoundingClientRect().height>50);
 if(blocks.length<2)blocks=[...document.querySelectorAll('section,header,footer')].filter(e=>e.getBoundingClientRect().height>50&&!e.parentElement?.closest('section'));
 const semantic=[...document.querySelectorAll('section,header,footer')].filter(e=>e.getBoundingClientRect().height>50&&!e.parentElement?.closest('section'));if(semantic.length>=2)blocks=semantic;
 const sections=blocks.map((e,i)=>{const s=getComputedStyle(e),r=rect(e),desc=[e,...e.querySelectorAll('*')];let largest=desc.reduce((a,n)=>parseFloat(getComputedStyle(n).fontSize)>parseFloat(getComputedStyle(a).fontSize)?n:a,e);const t=getComputedStyle(largest);return {index:i,key:key(e),landmark:e.id||e.getAttribute('data-section')||`section-${i}`,box:r,background:{color:s.backgroundColor,image:s.backgroundImage,video:!!e.querySelector('video')},columns:s.display.includes('grid')?s.gridTemplateColumns.split(' ').length:s.display==='flex'&&s.flexDirection==='row'?e.children.length:1,stickyFixed:desc.filter(n=>['fixed','sticky'].includes(getComputedStyle(n).position)).map(n=>({key:key(n),position:getComputedStyle(n).position,box:rect(n)})),font:{size:t.fontSize,family:t.fontFamily,weight:t.fontWeight,letterSpacing:t.letterSpacing,lineHeight:t.lineHeight},excerpt:e.textContent.trim().replace(/\s+/g,' ').slice(0,600),mediaCount:e.querySelectorAll('img,video,canvas,svg').length,fullBleed:r.width>=innerWidth-4}});
 // Overlaps stay inspectable while merged groups describe the actual vertical section topology.
 const groups=[];for(const s of [...sections].sort((a,b)=>a.box.top-b.box.top)){const last=groups.at(-1);if(last&&s.box.top<last.bottom-2){last.bottom=Math.max(last.bottom,s.box.top+s.box.height);last.members.push(s.landmark)}else groups.push({top:s.box.top,bottom:s.box.top+s.box.height,members:[s.landmark]})}
 const textBoxes=all.filter(e=>[...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())).map(e=>rect(e)).filter(r=>r.y<innerHeight&&r.y+r.height>0&&r.height>0&&r.width>0);const logoBoxes=[...document.querySelectorAll('[class*=logo],[id*=logo],img[alt*=logo i],.brand,.brand img,header img')].map(e=>rect(e)).filter(r=>r.y<innerHeight&&r.y+r.height>0&&r.width>0);return {url:location.href,textBoxes,logoBoxes,scrollY,maxScroll:Math.max(0,document.documentElement.scrollHeight-innerHeight),viewport:{width:innerWidth,height:innerHeight},sections,mergedSections:groups,motion,header:[...document.querySelectorAll('header')].map(e=>({key:key(e),box:rect(e),padding:getComputedStyle(e).padding})),links:[...document.querySelectorAll('a[href]')].map(e=>({text:e.textContent.trim().slice(0,100),href:e.href})),overflow:document.documentElement.scrollWidth>innerWidth+2};
 })}
async function settle(page,{timeout=2600,interval=180}={}){let previous=null,attempts=0,last;const start=Date.now();do{last=await page.screenshot({scale:'css',type:'png'});attempts++;if(previous&&last.equals(previous))return {settled:true,attempts,elapsedMs:Date.now()-start,image:last};previous=last;await page.waitForTimeout(interval)}while(Date.now()-start<timeout);return {settled:false,attempts,elapsedMs:Date.now()-start,image:last,reason:'No exact consecutive PNG match within bounded settle window; continuous or unfinished motion may remain.'}}
function deltas(a,b){const prior=new Map(a.motion.map(e=>[e.key,e]));return b.motion.flatMap(e=>{const p=prior.get(e.key);if(!p)return[];const changes={};for(const k of ['transform','opacity','filter','clipPath','color'])if(p[k]!==e[k])changes[k]={from:p[k],to:e[k]};const sticky=['sticky','fixed'].includes(e.position)&&Math.abs(p.y-e.y)<2&&Math.abs(a.scrollY-b.scrollY)>10;return Object.keys(changes).length||sticky?[{key:e.key,changes,stickyObserved:sticky,fromScroll:a.scrollY,toScroll:b.scrollY}]:[]})}
export async function captureSite(options){
 const {url,outDir,mode='screen',viewports=['desktop','tablet','phone'],videoSeconds=0,settleMs=mode==='deep'?2600:1200,maxSteps=500,sceneStates=[]}=options;
 await fs.mkdir(outDir,{recursive:true});const browser=options.browser||await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const manifest={schema:1,url,date:new Date().toISOString(),mode,browser:browser.version(),viewports:{},limits:['Computed motion evidence does not establish exact source easing or timing.','Automated screenshots require separate human/vision fidelity review.','Frames with settled:false are not stationary-state evidence.'],status:'Captured'};
 try{for(const name of viewports){const viewport=typeof name==='string'?VIEWPORTS[name]:name;if(!viewport)throw Error('Unknown viewport '+name);const label=typeof name==='string'?name:`${viewport.width}x${viewport.height}`,dir=path.join(outDir,label);await fs.mkdir(dir,{recursive:true});const context=await browser.newContext({viewport,deviceScaleFactor:1,reducedMotion:options.reducedMotion||'no-preference'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const record={viewport,dpr:1,reducedMotion:options.reducedMotion||'no-preference',states:[],motionDeltas:[],hover:[],errors};manifest.viewports[label]=record;
 try{const response=await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});record.httpStatus=response?.status();record.resolvedUrl=page.url();await page.evaluate(()=>Promise.race([document.fonts.ready,new Promise(r=>setTimeout(r,4000))]));await page.waitForTimeout(options.initialWaitMs??1200);
 const save=async(id,extra={})=>{const current=page.url();if(!options.allowAutomaticNavigation&&new URL(current).pathname!==new URL(record.resolvedUrl).pathname){record.routeChange={from:record.resolvedUrl,to:current,beforeState:id,reason:'Automatic navigation during scroll; subsequent states excluded from this route.'};throw Error('Route changed during capture: '+current)}const ready=await settle(page,{timeout:settleMs});const data=await snapshot(page);const file=path.join(dir,slug(id)+'.png');await fs.writeFile(file,ready.image);const state={id,capturedAt:new Date().toISOString(),file:path.resolve(file),settled:ready.settled,settleAttempts:ready.attempts,settleMs:ready.elapsedMs,...extra,...data};const prior=record.states.at(-1);if(prior)record.motionDeltas.push({from:prior.id,to:id,changes:deltas(prior,state)});record.states.push(state);return state};
 const first=await save('opening',{landmark:'opening',progress:0});if(options.menuSelector){const button=page.locator(options.menuSelector).first();if(await button.isVisible().catch(()=>false)){await button.click();await page.waitForTimeout(300);await save('menu-open',{landmark:'menu',progress:1});await page.keyboard.press('Escape');await page.waitForTimeout(200);record.menuChecked=true}else record.menuChecked=false}for(const held of options.heldStates||[]){await page.evaluate(y=>scrollTo(0,y),held.scrollY);for(const delay of held.delays||[0,500,1500,3000]){await page.waitForTimeout(delay);await save('held-'+held.scrollY+'-'+delay,{pass:'held',requestedScroll:held.scrollY,delaySincePreviousMs:delay})}}if(options.heldStates?.length)await page.evaluate(()=>scrollTo(0,0));record.links=first.links;record.sections=first.sections;let y=0,step=0,max=first.maxScroll;while(y<max&&step<maxSteps){const distance=Math.min(viewport.height/2,max-y);await page.mouse.wheel(0,distance);await page.waitForTimeout(mode==='deep'?240:100);let actual=await page.evaluate(()=>scrollY);if(actual<=y+1){await page.evaluate(v=>scrollTo(0,v),y+distance);await page.waitForTimeout(150);actual=await page.evaluate(()=>scrollY)}y=actual;step++;if(mode==='deep')await save('forward-'+String(step).padStart(3,'0'),{pass:'slow'});max=await page.evaluate(()=>Math.max(0,document.documentElement.scrollHeight-innerHeight));if(max-y<2)break}
 record.truncated=step>=maxSteps&&y<max-2;await save('footer',{landmark:'footer',progress:1});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(1200);await save('opening-settled',{landmark:'opening-after-traversal',progress:0});await page.evaluate(v=>scrollTo(0,v),max/2);await page.waitForTimeout(200);await save('midpoint',{landmark:'midpoint',progress:.5});
 if(mode==='deep'){
 // Section landmarks, quarter scene states and both sides of sticky/pin boundaries.
 const sections=(await snapshot(page)).sections;for(const s of sections){await page.evaluate(v=>scrollTo(0,v),Math.max(0,s.box.top));await save('section-'+slug(s.landmark),{landmark:s.landmark,progress:0});const end=Math.max(s.box.top,s.box.top+s.box.height-viewport.height);if(s.stickyFixed.length&&end>s.box.top){for(const progress of [0,.25,.5,.75,1]){await page.evaluate(v=>scrollTo(0,v),s.box.top+(end-s.box.top)*progress);await save(slug(s.landmark)+'-p'+progress,{landmark:s.landmark,progress})}for(const [suffix,pos]of[['before',s.box.top-2],['after',end+2]]){await page.evaluate(v=>scrollTo(0,v),Math.max(0,pos));await save(slug(s.landmark)+'-'+suffix,{landmark:s.landmark,boundary:suffix})}}}
 for(const scene of sceneStates){for(const progress of scene.testStates||[0,.25,.5,.75,1]){const inspected=await page.evaluate(async({id,progress})=>{const i=window.__motionInspector;if(!i)return false;await i.ready();await i.seekScene(id,progress);return i.getSceneState(id)},{id:scene.id,progress});if(inspected)await save('scene-'+slug(scene.id)+'-'+progress,{landmark:scene.id,progress,inspector:inspected});else(record.unknownScenes??=[]).push(scene.id)}}
 await page.evaluate(()=>scrollTo(0,0));await page.mouse.wheel(0,max);await page.waitForTimeout(160);await save('fast-end',{pass:'fast'});for(let pos=max;pos>0;pos-=viewport.height/2){await page.mouse.wheel(0,-viewport.height/2);await page.waitForTimeout(180);if(record.states.length<120)await save('reverse-'+Math.round(pos),{pass:'reverse'})}await page.evaluate(()=>scrollTo(0,0));await save('reverse-opening',{pass:'reverse'});
 const interactive=page.locator('a,button,summary,input,select,textarea');for(let i=0;i<Math.min(10,await interactive.count());i++){const el=interactive.nth(i);if(!await el.isVisible())continue;await el.scrollIntoViewIfNeeded();const before=await snapshot(page);await el.hover({timeout:2000}).catch(()=>{});await page.waitForTimeout(350);const after=await save('hover-'+i,{pass:'hover'});record.hover.push({index:i,text:(await el.textContent())?.slice(0,100),changes:deltas(before,after)});await page.mouse.move(viewport.width-1,0)}
 await page.evaluate(()=>scrollTo(0,0));for(let i=0;i<6;i++){await page.keyboard.press('Tab');record.keyboard??=[];record.keyboard.push(await page.evaluate(()=>({tag:document.activeElement?.tagName,text:document.activeElement?.textContent?.slice(0,100),visible:!!document.activeElement?.getBoundingClientRect().height})))}
 }
 // Explicitly label layout-only CSS disabling; it does not freeze JS/video.
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(dir,'layout-full.png'),fullPage:true,scale:'css',animations:'disabled'});record.layoutFull=path.resolve(dir,'layout-full.png');record.sections=(await snapshot(page)).sections;
 if(videoSeconds){const vc=await browser.newContext({viewport,deviceScaleFactor:1,recordVideo:{dir:path.join(dir,'video'),size:viewport}});const vp=await vc.newPage();await vp.goto(url,{waitUntil:'domcontentloaded'});await vp.waitForTimeout(400);const video=vp.video();const duration=Math.max(10,Math.min(20,videoSeconds))*1000;const start=Date.now();while(Date.now()-start<duration){const p=(Date.now()-start)/duration;await vp.evaluate(p=>scrollTo(0,(document.documentElement.scrollHeight-innerHeight)*(p<.72?p/.72:(1-p)/.28)),p);await vp.waitForTimeout(70)}await vc.close();record.video=await video.path();record.videoDurationRequested=duration/1000}
 }catch(error){record.error=String(error);manifest.status='Captured-with-errors'}finally{await context.close()}
 await fs.writeFile(path.join(dir,'capture.json'),JSON.stringify(record,null,2));}
 }finally{if(!options.browser)await (async()=>{let timer;await Promise.race([browser.close(),new Promise(r=>{timer=setTimeout(()=>{manifest.limits.push('Browser shutdown exceeded15seconds; capture records saved before cleanup completed.');r()},15000)})]);clearTimeout(timer)})()}
 await fs.writeFile(path.join(outDir,'manifest.json'),JSON.stringify(manifest,null,2));return manifest;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){const args=Object.fromEntries(process.argv.slice(2).reduce((a,v,i,arr)=>v.startsWith('--')?[...a,[v.slice(2),arr[i+1]?.startsWith('--')?true:arr[i+1]||true]]:a,[]));if(!args.url||!args.out)throw Error('Usage: node --experimental-strip-types scripts/capture.ts --url URL --out DIR [--mode screen|deep] [--viewports desktop,tablet,phone] [--video 15]');const m=await captureSite({url:args.url,outDir:args.out,mode:args.mode||'screen',viewports:(args.viewports||'desktop,tablet,phone').split(','),videoSeconds:Number(args.video||0),settleMs:Number(args.settle||1200)});console.log(JSON.stringify({status:m.status,manifest:path.resolve(args.out,'manifest.json'),viewports:Object.keys(m.viewports)}))}
