/** Landmark-aligned comparison evidence. Never produces a content-insensitive similarity score. */
import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const escape=s=>String(s).replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));
export async function contactSheet({images,out,width=480,columns=3,grayscale=false,blurCopy=false,removeLogos=false}){
 const tiles=[];for(const item of images){let p=sharp(item.file).resize({width,withoutEnlargement:false});if(grayscale)p=p.grayscale();let buf=await p.png().toBuffer();const meta=await sharp(buf).metadata();if(blurCopy&&item.textBoxes?.length){const original=await sharp(item.file).metadata(),ratio=width/original.width;const overlays=[];for(const b of item.textBoxes){let x=Math.max(0,Math.round(b.x*ratio)),y=Math.max(0,Math.round(b.y*ratio)),w=Math.min(width-x,Math.round(b.width*ratio)),h=Math.min(meta.height-y,Math.round(b.height*ratio));if(w>0&&h>0)overlays.push({input:await sharp(buf).extract({left:x,top:y,width:w,height:h}).blur(12).png().toBuffer(),left:x,top:y})}if(overlays.length)buf=await sharp(buf).composite(overlays).png().toBuffer()}
 if(removeLogos&&item.logoBoxes?.length){const original=await sharp(item.file).metadata(),ratio=width/original.width;const patches=item.logoBoxes.map(b=>({left:Math.max(0,Math.round(b.x*ratio)),top:Math.max(0,Math.round(b.y*ratio)),width:Math.min(width-Math.max(0,Math.round(b.x*ratio)),Math.round(b.width*ratio)),height:Math.min(meta.height-Math.max(0,Math.round(b.y*ratio)),Math.round(b.height*ratio))})).filter(b=>b.width>0&&b.height>0);if(patches.length)buf=await sharp(buf).composite(patches.map(b=>({input:Buffer.from(`<svg width="${b.width}" height="${b.height}"><rect width="100%" height="100%" fill="#888"/></svg>`),left:b.left,top:b.top}))).png().toBuffer()}
 const label=Buffer.from(`<svg width="${width}" height="44"><rect width="100%" height="100%" fill="#f5f4ef"/><text x="10" y="27" font-family="sans-serif" font-size="13" fill="#111">${escape(item.label||path.basename(item.file)).slice(0,100)}</text></svg>`);tiles.push({buf,height:meta.height,label})}
 const rows=Math.ceil(tiles.length/columns),rowHeights=Array.from({length:rows},(_,r)=>Math.max(...tiles.slice(r*columns,r*columns+columns).map(t=>t.height))+44);const composites=[];let y=0;for(let r=0;r<rows;r++){for(let c=0;c<columns;c++){const t=tiles[r*columns+c];if(t){composites.push({input:t.label,left:c*width,top:y},{input:t.buf,left:c*width,top:y+44})}}y+=rowHeights[r]}
 await fs.mkdir(path.dirname(out),{recursive:true});await sharp({create:{width:columns*width,height:y,channels:3,background:'#e5e5e2'}}).composite(composites).png().toFile(out);return path.resolve(out);
}
export function structuralAssertions({reference,build,sectionPairs=[],blueprintSectionCount}){
 const checks=[];for(const [viewport,actual]of Object.entries(build.viewports)){const source=reference.viewports[viewport];if(!source)continue;const a=actual.sections||[],r=source.sections||[];
 if(blueprintSectionCount!==undefined)checks.push({viewport,test:'section-count-within-one-of-blueprint',pass:Math.abs(a.length-blueprintSectionCount)<=1,actual:a.length,expected:blueprintSectionCount});
 for(const pair of sectionPairs){const x=a.find(s=>s.landmark===pair.build),y=r.find(s=>s.landmark===pair.reference);if(!x||!y){checks.push({viewport,test:'section-pair-present',pass:false,pair});continue}const ratioX=x.box.height/x.box.width,ratioY=y.box.height/y.box.width;checks.push({viewport,pair,test:'section-aspect-within-15-percent',pass:Math.abs(ratioX/ratioY-1)<=.15,actual:ratioX,reference:ratioY},{viewport,pair,test:'full-bleed-matches',pass:x.fullBleed===y.fullBleed,actual:x.fullBleed,reference:y.fullBleed},{viewport,pair,test:'sticky-presence-matches',pass:!!x.stickyFixed.length===!!y.stickyFixed.length,actual:x.stickyFixed.length,reference:y.stickyFixed.length});}}
 return {checks,limit:'Only explicit semantic section pairs tested. Typography and actual-pixel ground alternation require additional measurements; no visual fidelity score inferred.'};
}
export function motionAssertions({manifest,contracts}){const checks=[];for(const [viewport,record]of Object.entries(manifest.viewports))for(const c of contracts){const states=record.states.filter(s=>s.landmark===c.scene);for(const target of c.targets){for(const property of target.properties){const values=states.map(s=>s.motion.find(m=>m.key===target.key)?.[property]).filter(v=>v!==undefined);checks.push({viewport,scene:c.scene,target:target.key,property,pass:values.length>=2&&new Set(values).size>1,values,test:'declared-property-observed-changing'});}}}return {checks,limit:'A changing property does not prove timing, monotonicity, aesthetics, or complete scene fidelity.'};}
export async function compareCaptures({reference,build,outDir,pairs,topExamples=[]}){const ref=typeof reference==='string'?JSON.parse(await fs.readFile(reference,'utf8')):reference;const actual=typeof build==='string'?JSON.parse(await fs.readFile(build,'utf8')):build;await fs.mkdir(outDir,{recursive:true});const result={created:new Date().toISOString(),pairs:[],unmatched:[],judgment:'Unreviewed — generated comparisons do not establish visual fidelity.'};
 for(const [vp,data]of Object.entries(actual.viewports)){const rd=ref.viewports[vp];if(!rd){result.unmatched.push({viewport:vp,reason:'Reference viewport missing'});continue}const assignments=pairs||data.states.filter(s=>s.landmark).map(s=>({build:s.id,reference:rd.states.find(r=>r.landmark===s.landmark&&r.progress===s.progress)?.id}));for(const pair of assignments){const a=data.states.find(s=>s.id===pair.build),r=rd.states.find(s=>s.id===pair.reference);if(!a||!r){result.unmatched.push({viewport:vp,...pair,reason:'No matched landmark and scene progress; no scroll-percentage substitute inferred'});continue}const out=path.join(outDir,`${vp}-${a.id}.png`);await contactSheet({images:[{file:r.file,label:`Reference | ${r.landmark||r.id} | ${r.progress??''}`},{file:a.file,label:`Build | ${a.landmark||a.id} | ${a.progress??''}`}],out,width:vp==='phone'?390:720,columns:2});result.pairs.push({viewport:vp,referenceState:r.id,buildState:a.id,file:path.resolve(out),referenceSettled:r.settled,buildSettled:a.settled});}
 if(topExamples.length===3){const a=data.states.find(s=>s.id==='opening');const files=topExamples.map(m=>m.viewports?.[vp]?.states?.find(s=>s.id==='opening')).filter(Boolean);if(a&&files.length===3)await contactSheet({images:[{file:files[0].file,label:'Top example 1'},{file:a.file,label:'Build'},{file:files[1].file,label:'Top example 2'},{file:files[2].file,label:'Top example 3'}],out:path.join(outDir,`${vp}-top-examples.png`),width:390,columns:4})}}
 await fs.writeFile(path.join(outDir,'comparison.json'),JSON.stringify(result,null,2));return result;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){const a={};for(let i=2;i<process.argv.length;i+=2)a[process.argv[i].replace(/^--/,'')]=process.argv[i+1];if(a.sheet){const items=JSON.parse(await fs.readFile(a.sheet,'utf8'));console.log(await contactSheet({images:items,out:a.out,width:Number(a.width||480),columns:Number(a.columns||3),grayscale:a.grayscale==='true',blurCopy:a['blur-copy']==='true',removeLogos:a['remove-logos']==='true'}))}else{if(!a.reference||!a.build||!a.out)throw Error('Usage: compare.ts --reference manifest.json --build manifest.json --out DIR [--pairs pairs.json]; or --sheet images.json --out FILE --grayscale true');const r=await compareCaptures({reference:a.reference,build:a.build,outDir:a.out,pairs:a.pairs?JSON.parse(await fs.readFile(a.pairs,'utf8')):undefined});console.log(JSON.stringify({pairs:r.pairs.length,unmatched:r.unmatched.length,out:a.out}))}}
