// Release contract for the Framer-informed full-journey redesign.
import{chromium}from'playwright';import fs from'node:fs';
const base=process.env.KLCC_BASE||'http://127.0.0.1:4197/';const data=JSON.parse(fs.readFileSync(new URL('../content.json',import.meta.url)));const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const errors=[];const rows=[];const assert=(ok,message)=>{if(!ok)errors.push(message)};
const norm=s=>s.replace(/programing designed for specifically for/g,'programming designed specifically for').replace(/first time visit/g,'first visit').replace(/Let us Know/g,'Let us know').replace(/in awhile/g,'in a while').replace(/(\d+)-(\d+)\s+th\b/gi,'$1th $2th').replace(/(\d)\s+th\b/gi,'$1th').replace(/[^\p{L}\p{N}]+/gu,' ').trim().toLowerCase();
for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:844}});for(const[route,source]of Object.entries(data.pages)){
 await page.goto(new URL(route==='/'?'':route.slice(1)+'/',base).href,{waitUntil:'domcontentloaded'});await page.locator('.site-header').waitFor();await page.evaluate(()=>document.fonts.ready);
 for(const progress of [0,.5,1]){await page.evaluate(p=>scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*p,behavior:'instant'}),progress);await page.waitForTimeout(300);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`${route} ${width}: overflow at ${progress}`)}
 const state=await page.evaluate(()=>({badImages:[...document.images].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src),oldLinks:[...document.querySelectorAll('a[href]')].filter(a=>/^https?:\/\/(www\.)?klcc\.us\b/i.test(a.href)).map(a=>a.href),badAnchors:[...document.querySelectorAll('a[href^="#"]')].filter(a=>a.hash.length>1&&!document.getElementById(a.hash.slice(1))).map(a=>a.hash)}));
 assert(!state.badImages.length,`${route} ${width}: broken images`);assert(!state.oldLinks.length,`${route} ${width}: old-site link`);assert(!state.badAnchors.length,`${route} ${width}: missing anchors ${state.badAnchors}`);
 if(route!=='/'){
 const rendered=norm(await page.locator('main p, main li').evaluateAll(es=>es.map(e=>e.textContent).join(' ')));
 const missing=source.sections.flatMap(s=>s.blocks.filter(b=>['p','li'].includes(b.type)&&b.text.length>30)).filter(b=>!rendered.includes(norm(b.text)));
 assert(!missing.length,`${route} ${width}: source paragraphs missing ${missing.map(b=>b.text.slice(0,50))}`);
 const fg=await page.locator('.detail-hero-links a').evaluateAll(es=>es.map(e=>getComputedStyle(e).color));assert(fg.every(c=>c==='rgb(20, 33, 43)'),`${route} ${width}: opening CTA contrast ${fg}`);
 }
 await page.locator('#menuButton').click();assert(await page.locator('#menuButton').getAttribute('aria-expanded')==='true',`${route} ${width}: menu failed`);await page.locator('.menu-panel a').first().waitFor({state:'visible'});assert(await page.locator('.menu-panel a').first().isVisible(),`${route} ${width}: menu links hidden`);await page.keyboard.press('Escape');assert(await page.locator('#menuPanel').getAttribute('aria-hidden')==='true',`${route} ${width}: menu escape failed`);rows.push({route,width,...state});
 }await page.close()}
const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto(new URL('new/',base).href,{waitUntil:'domcontentloaded'});assert(await page.locator('.detail-hero-links a').first().getAttribute('href')==='#section-5','New: What to expect wrong target');await page.goto(new URL('give/',base).href,{waitUntil:'domcontentloaded'});const giveTarget=await page.locator('.detail-hero-links a').first().getAttribute('href');assert((await page.locator(giveTarget+' h2').first().textContent()).trim()==='Ways to Give','Give: Ways to give wrong passage');await page.goto(new URL('leadership/',base).href,{waitUntil:'domcontentloaded'});await page.locator('.people-list summary').first().click();assert(await page.locator('.people-list details').first().getAttribute('open')!==null,'Leadership: biography inaccessible');
await page.goto(base,{waitUntil:'domcontentloaded'});const motion=await page.evaluate(async()=>{const el=document.querySelector('.outreach-layout figure');const y=el.getBoundingClientRect().top+scrollY;scrollTo({top:y-innerHeight*.85,behavior:'instant'});await new Promise(r=>setTimeout(r,150));const a=getComputedStyle(el).getPropertyValue('--depth-in');scrollTo({top:y-innerHeight*.15,behavior:'instant'});await new Promise(r=>setTimeout(r,150));const b=getComputedStyle(el).getPropertyValue('--depth-in');return [a,b]});assert(+motion[1]>+motion[0],'Outreach: image scroll reveal does not advance');
await page.close();const fallback=await browser.newPage({javaScriptEnabled:false});await fallback.goto(new URL('youth/',base).href,{waitUntil:'domcontentloaded'});assert(await fallback.locator('.detail-hero h1').isVisible(),'No-JS: page unreadable');assert(await fallback.locator('.menu-panel a').first().isVisible(),'No-JS: navigation missing');assert(await fallback.locator('.menu-panel').getAttribute('aria-hidden')!=='true','No-JS: navigation hidden from accessibility tree');await fallback.close();await browser.close();
if(process.env.KLCC_REPORT)fs.writeFileSync(process.env.KLCC_REPORT,JSON.stringify({base,rows,errors},null,2));if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log('PASS: 28 routes × desktop/tablet/phone; complete inner copy; valid local actions; menus; biography; image motion; no-JS.');
