/** Automatic evidence checks. Unknown/absent evidence is Blocked, never a visual pass.
 * Run: node scripts/gates.ts [--gate G0] [--out art-direction/qa/gates.json]
 * Static checks supplement browser/vision review; they do not certify visual quality.
 */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..'); const ad=path.join(root,'art-direction');
const exists=(p:string)=>fs.existsSync(path.join(root,p));
const read=(p:string)=>{try{return JSON.parse(fs.readFileSync(path.join(root,p),'utf8'))}catch{return null}};
const walk=(p:string):string[]=>fs.existsSync(p)?fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]):[];
const results:any[]=[];function check(gate:string,name:string,pass:boolean|null,evidence:any){results.push({gate,name,status:pass===null?'Blocked':pass?'Pass':'Fail',evidence})}
const ledger=read('art-direction/content-ledger.json');const truth=read('art-direction/company-truth.json');
check('G0','Inventory exists',!!ledger,'art-direction/content-ledger.json');
check('G0','Original content unchanged',ledger?ledger.content_file_sha256===crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'content.json'))).digest('hex'):null,'content.json');
check('G0','Protected skill baseline exists',exists('art-direction/protected-skills.json'),'art-direction/protected-skills.json');
check('G1','Company truth with source dates',!!truth&&truth.facts.every((f:any)=>f.source&&f.capture_date),'art-direction/company-truth.json');
check('G1','All original routes fetched live',truth?truth.sources.every((s:any)=>s.status===200):null,truth?.sources);
// G4 is a historical gate: later success cannot erase building the remaining pages early.
const pilotRoutes=['our-story','mission'];const pilotFindings:any[]=[];const reviewTimes:number[]=[];
for(const route of pilotRoutes){
 const file=`art-direction/qa/fidelity/${route}.json`;const f=read(file);
 if(!f){pilotFindings.push({route,issue:'missing Fidelity record',file});continue}
 if(f.status!=='Fidelity-reviewed')pilotFindings.push({route,issue:'status is not Fidelity-reviewed',actual:f.status});
 const when=Date.parse(f.reviewed_at||'');if(!Number.isFinite(when))pilotFindings.push({route,issue:'reviewed_at missing/invalid'});else reviewTimes.push(when);
 const sections=f.sections||[];if(!sections.length)pilotFindings.push({route,issue:'section scores missing'});
 for(const section of sections){const scored=section.reviews||section.states||[section];for(const state of scored){const scores=state.scores||state.rubric||{};const values=Object.values(scores);if(values.length<10||values.some(v=>typeof v!=='number'||v<4||v>5))pilotFindings.push({route,section:section.id,issue:'ten required rubric dimensions must each score4–5',scores});const evidence=state.comparison||state.side_by_side||section.comparison;if(typeof evidence!=='string'||!exists(evidence))pilotFindings.push({route,section:section.id,issue:'missing comparison image',evidence});}}
 const vps=new Set(sections.flatMap((s:any)=>(s.reviews||s.states||[s]).map((v:any)=>String(v.viewport?.width||v.viewport||''))));for(const vp of ['1440','1024','390'])if(![...vps].some(x=>x.includes(vp)))pilotFindings.push({route,issue:'missing viewport rubric evidence',viewport:vp});
}
check('G4','Both hardest pilots Fidelity-reviewed with section evidence',pilotFindings.some(x=>x.issue==='missing Fidelity record')?null:pilotFindings.length===0,pilotFindings);
let events:any[]=[];try{events=fs.readFileSync(path.join(ad,'build-events.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(x=>JSON.parse(x))}catch{}
const later=events.filter(e=>e.event==='build'&&!pilotRoutes.includes(e.route)&&e.route!=='home');
const premature=later.filter(e=>reviewTimes.length!==2||!Number.isFinite(Date.parse(e.at))||Date.parse(e.at)<Math.max(...reviewTimes));
check('G4','Pilot review preceded remaining authored page builds',!events.length||reviewTimes.length!==2?null:premature.length===0,{events:'art-direction/build-events.jsonl',premature,note:'Legacy pre-run pages excluded; only this run timestamped build events establish chronology.'});
const bpFiles=walk(path.join(ad,'pages')).filter(p=>p.endsWith('/blueprint.json'));const bps=bpFiles.map(f=>JSON.parse(fs.readFileSync(f,'utf8')));
const expected=new Set<string>((ledger?.items||[]).filter((i:any)=>i.required!==false).map((i:any)=>i.id));
const references=new Set<string>();for(const bp of bps){const serialized=JSON.stringify(bp.sections||[]);for(const id of serialized.match(/(?:ci|cta|img):[a-zA-Z0-9_.:-]+/g)||[])references.add(id)}
const missing=[...expected].filter(id=>!references.has(id));const allKnown=new Set<string>((ledger?.items||[]).map((i:any)=>i.id));const unknown=[...references].filter(id=>!allKnown.has(id));
check('G5','Content ledger mapped to sections',bps.length?missing.length===0&&unknown.length===0:null,{missing,unknown,blueprints:bpFiles.map(f=>path.relative(root,f))});
const routes=ledger?.routes||[];
check('G5','All route blueprints exist',routes.length?routes.every((r:any)=>bps.some(b=>b.route===r.route)):null,{missing:routes.filter((r:any)=>!bps.some(b=>b.route===r.route)).map((r:any)=>r.route)});
const ml=read('art-direction/motion-ledger.json');const motions=Array.isArray(ml)?ml:ml?.pages||ml?.routes||[];const marr=Array.isArray(motions)?motions:Object.entries(motions).map(([route,v]:any)=>({route,...v}));
const collisions:any[]=[];for(let a=0;a<marr.length;a++)for(let b=a+1;b<marr.length;b++){const x=marr[a].heading_arrival||marr[a].headingArrival,y=marr[b].heading_arrival||marr[b].headingArrival;if(!x||!y){collisions.push({routes:[marr[a].route,marr[b].route],reason:'missing heading axes'});continue}const differences=['unit','vector','driver'].filter(k=>x[k]!==y[k]);if(differences.length<2)collisions.push({routes:[marr[a].route,marr[b].route],differences})}
check('G6','Heading arrival differs on two axes',marr.length?collisions.length===0:null,{collisions,note:'No random axes may be assigned to pass; DOM evidence is separately required.'});
const split=marr.filter(x=>['word','line','character'].includes((x.heading_arrival||x.headingArrival)?.unit));check('G6','At most one third split headings',marr.length?split.length<=marr.length/3:null,{split:split.map(x=>x.route),total:marr.length});
const sigs=marr.map(x=>x.signature?.id||x.signature);check('G6','Unique page signatures',marr.length?new Set(sigs).size===sigs.length:null,sigs);
// Source lint only project runtime; old files can exist in history but active routes must not import them.
const codeFiles=walk(path.join(root,'src')).filter(f=>/\.(?:js|ts|css|astro|tsx)$/.test(f));const lint:any[]=[];
for(const f of codeFiles){const s=fs.readFileSync(f,'utf8');const rel=path.relative(root,f);for(const [name,re]of [['banned-font',/Fraunces/i],['generic-renderer',/InnerPageRenderer|openingFamily|bodyFamily/],['global-heading-motion',/(?:querySelectorAll|gsap\.(?:to|from|fromTo))\s*\(\s*['"`]h[12](?:\s*,|['"`])/],['excess-reading-measure',/(?:max-)?width\s*:\s*(?:7[6-9]|[89]\d|\d{3,})ch\b/],['decorative-arrow',/↗/],['banned-orb',/(?:purple|indigo|cyan)[\w\s-]{0,20}(?:glow|orb)/]]as [string,RegExp][]){if(re.test(s))lint.push({file:rel,rule:name})}if(/opacity\s*:\s*0(?:[;}])/.test(s)&&!/prefers-reduced-motion|reducedMotion|reduced-motion/.test(s))lint.push({file:rel,rule:'opacity-zero-needs-browser-fallback-check',severity:'review'})}
check('G6','Anti-slop source assertions',codeFiles.length?lint.filter(x=>x.severity!=='review').length===0:null,{files:codeFiles.length,findings:lint});
const structural=read('art-direction/qa/structural-results.json');check('G6','Measured structural assertions',structural?.checks?.length?structural.checks.every((c:any)=>c.pass===true):null,{path:'art-direction/qa/structural-results.json',required:['section count ±1','section aspect ±15%','full bleed','sticky/pin','h1 viewport ratio ±20%','ground alternation'],note:'Must compare reference and build DOM section measurements, not declarations.'});
const deltas=read('art-direction/qa/motion-results.json');check('G6','Observed motion properties match contracts',deltas?.checks?.length?deltas.checks.every((c:any)=>c.pass===true):null,'art-direction/qa/motion-results.json');
const ship:any[]=[];for(const r of routes){const file=r.route==='home'?'index.html':r.route==='404'?(exists('404.html')?'404.html':'404/index.html'):`${r.route}/index.html`;if(!exists(file)){ship.push({route:r.route,missing:file});continue}const h=fs.readFileSync(path.join(root,file),'utf8');for(const [name,re]of [['title',/<title>[^<]+<\/title>/i],['description',/<meta[^>]+name=["']description["'][^>]+content=/i],['favicon',/<link[^>]+rel=["'](?:shortcut )?icon["']/i],['og',/<meta[^>]+property=["']og:title["']/i]]as[string,RegExp][]){if(!re.test(h))ship.push({route:r.route,missing:name})}const imgs=h.match(/<img\b[^>]*>/gi)||[];for(const i of imgs)if(!/\balt\s*=/.test(i))ship.push({route:r.route,missing:'image alt',image:i.slice(0,150)});if(/(?:src|href)=["']https?:\/\/(?:www\.)?klcc\.us\//.test(h))ship.push({route:r.route,missing:'local marketing migration'})}
for(const p of ['robots.txt','sitemap.xml'])if(!exists(p))ship.push({missing:p});check('G7','Ship metadata/routes/alt',routes.length?ship.length===0:null,ship);
const webp=ledger?.items.filter((i:any)=>i.type==='image'&&!/\.webp$|\.avif$|\.svg$/.test(i.path))||[];check('G7','Optimized asset variants available',webp.length?webp.every((i:any)=>exists(i.path.replace(/\.[^.]+$/,'.webp'))||exists(i.path.replace(/\.[^.]+$/,'.avif'))):null,{need_variants:webp.filter((i:any)=>!exists(i.path.replace(/\.[^.]+$/,'.webp'))&&!exists(i.path.replace(/\.[^.]+$/,'.avif'))).map((i:any)=>i.path)});
for(const [gate,p]of [['G2','art-direction/references/pool-screening.md'],['G2','art-direction/directions.md'],['G2','art-direction/site-dna.json'],['G2','art-direction/uniqueness.json'],['G3','art-direction/references'],['G8','COMPLETION.md'],['G8','pending-proposals.md'],['G8','art-direction/qa/self-review.md']]as[string,string][])check(gate,`Artifact ${p}`,exists(p),p);
const fid=walk(path.join(ad,'qa/fidelity')).filter(p=>p.endsWith('.json'));check('G6','Per-route reviewed evidence exists',routes.length?routes.every((r:any)=>fid.some(p=>path.basename(p,'.json')===r.route)):null,{files:fid.map(f=>path.relative(root,f)),note:'Existence does not approve rubric scores; reviewer must inspect actual captures.'});
const fidelityFailures:any[]=[];for(const route of routes){const f=read(`art-direction/qa/fidelity/${route.route}.json`);if(!f||f.status!=='Fidelity-reviewed'){fidelityFailures.push({route:route.route,status:f?.status||'Missing',evidence:`art-direction/qa/fidelity/${route.route}.json`});continue}for(const sec of f.sections||[])for(const state of sec.reviews||sec.states||[sec]){const values=Object.values(state.scores||state.rubric||{});if(values.length&&values.some((x:any)=>typeof x!=='number'||x<4))fidelityFailures.push({route:route.route,section:sec.id,issue:'Score below 4'})}}check('G6','Every route meets independent reference fidelity',fidelityFailures.length===0,fidelityFailures);
const filter=process.argv.includes('--gate')?process.argv[process.argv.indexOf('--gate')+1]:null;const selected=filter?results.filter(r=>r.gate===filter):results;const outArg=process.argv.indexOf('--out');const out=path.join(root,outArg>=0?process.argv[outArg+1]:'art-direction/qa/gates.json');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify({version:'2.2',checked_at:new Date().toISOString(),scope:filter||'all',status:selected.every(r=>r.status==='Pass')?'Pass':'Blocked',results:selected},null,2));console.log(JSON.stringify({out:path.relative(root,out),pass:selected.filter(r=>r.status==='Pass').length,fail:selected.filter(r=>r.status==='Fail').length,blocked:selected.filter(r=>r.status==='Blocked').length}));process.exitCode=selected.every(r=>r.status==='Pass')?0:1;
