/** Source-backed snapshot of original public KLCC media categories. No inferred classification. */
import fs from 'node:fs/promises';
const root=new URL('../',import.meta.url);const categories=['topic','speaker','scripture'];
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const catalog:any={generated_at:new Date().toISOString(),source:'https://klcc.us/media/',source_pagination_script:'https://assets2.snappages.site/global/assets/js/website.min.js?v=1788471133',method:'Published original category names; original read-only getMediaItems pagination endpoint with method/value filters. Static snapshot, not live provider search.',categories:{},items:{},limitations:['Provider-hosted topic/speaker/scripture routes were not verified; local category membership is copied from original published classifications.','This catalog reflects the source snapshot date and does not automatically update when KLCC publishes new messages.','Original artwork URLs are provider-owned; this catalog does not certify rights.']};
async function group(kind:string,g:any){const rows:any[]=[];let total=0;const requests=[];for(let page=1;page<200;page++){const params={action:'getMediaItems',website_id:'23231',method:kind,value:g.value,page:String(page),limit:'100'};const response=await fetch('https://klcc.us/controllers/subsplash',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});if(!response.ok)throw Error('Media fetch '+response.status);const data=await response.json();if(!data._embedded?.['media-items'])throw Error('Unexpected media shape '+kind+g.value);total=Number(data.total);requests.push({endpoint:'https://klcc.us/controllers/subsplash',parameters:params,count:data.count,total});rows.push(...data._embedded['media-items']);if(rows.length>=total||!data.count)break;}
const published=await (await fetch('https://klcc.us'+g.path)).text();const publishedTotal=Number(published.match(/data-total="(\d+)"/)?.[1]??NaN);const publishedIds=[...published.matchAll(/class="sp-media-item" href="\/media\/([^/]+)\//g)].map(m=>m[1]);if(kind==='speaker'){rows.length=0;rows.push(...allMedia.filter(m=>m.speaker===g.value));total=publishedTotal;requests.push({method:'Full published library exact speaker field',value:g.value,library_count:allMedia.length});}const ids=[...new Set(rows.map(m=>m.short_code))];const source_page_check={total:publishedTotal,first_page_ids:publishedIds,all_first_page_ids_present:publishedIds.every(id=>ids.includes(id)),total_matches:publishedTotal===total};for(const m of rows){const image=m._embedded?.images?.find((i:any)=>i.type==='wide');const template=image?._links?.dynamic?.href;catalog.items[m.short_code]={id:m.short_code,title:m.title,date:m.date??null,speaker:m.speaker??null,description:m.summary_text??null,provider_url:'https://subsplash.com/+7664/lb/mi/+'+m.short_code,artwork:template?.replace('{name}.{ext}','image.jpg').replace('{width}','800').replace('{height}','450')??null};}return {...g,source:'https://klcc.us'+g.path,source_total:total,item_ids:ids,complete:ids.length===total&&source_page_check.total_matches&&source_page_check.all_first_page_ids_present,source_page_check,requests};}
// Full published library exposes canonical speaker metadata; filtered speaker endpoint is stale.
const allMedia:any[]=[];for(let page=1;page<100;page++){const params=new URLSearchParams({action:'getMediaItems',website_id:'23231',page:String(page),limit:'100'});const d=await (await fetch('https://klcc.us/controllers/subsplash',{method:'POST',body:params})).json();allMedia.push(...d._embedded['media-items']);if(allMedia.length>=d.total)break;}
catalog.library_count=allMedia.length;
for(const kind of categories){const h=await fs.readFile(new URL('art-direction/source/media-'+kind+'.html',root),'utf8');const groups=[...h.matchAll(/<a href="([^"]+)" class="sp-tag-item" data-count="(\d+)">([^<]+)<\/a>/g)].map(m=>({label:decode(m[3]),path:decode(m[1]),value:decodeURIComponent(m[1].split('/').at(-1)!.replace(/\+/g,' ')),index_count:Number(m[2])}));catalog.categories[kind]=[];for(let i=0;i<groups.length;i+=3){catalog.categories[kind].push(...await Promise.all(groups.slice(i,i+3).map(g=>group(kind,g))));}console.log(kind,catalog.categories[kind].map((g:any)=>[g.label,g.item_ids.length,g.complete]));}
await fs.mkdir(new URL('assets/data/',root),{recursive:true});await fs.writeFile(new URL('assets/data/media-catalog.json',root),JSON.stringify(catalog,null,2));console.log('Items',Object.keys(catalog.items).length);
