import fs from 'node:fs';import {chromium,webkit}from'playwright';
const base='http://127.0.0.1:4201';const routes=JSON.parse(fs.readFileSync('art-direction/content-ledger.json','utf8')).routes.map((r:any)=>r.route);const report:any={created:new Date().toISOString(),physicalPhonesTested:false,limits:['Local Chrome4xCPU lab proxies, not field Web Vitals or physical phone validation.','No financial transactions or forms submitted.','Third-party media may require service consent; direct service fallbacks verified separately.'],lab:[],nojs:[],interactions:[],webkit:[]};const save=()=>fs.writeFileSync('art-direction/qa/resilience.json',JSON.stringify(report,null,2));
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
await page.addInitScript(()=>{(window as any).__lab={lcp:0,cls:0,longTasks:[],events:[]};for(const[type,fn]of [['largest-contentful-paint',(e:any)=>(window as any).__lab.lcp=e.startTime],['layout-shift',(e:any)=>{if(!e.hadRecentInput)(window as any).__lab.cls+=e.value}],['longtask',(e:any)=>(window as any).__lab.longTasks.push(e.duration)],['event',(e:any)=>(window as any).__lab.events.push({name:e.name,duration:e.duration})]]as any){try{new PerformanceObserver(list=>list.getEntries().forEach(fn)).observe({type,buffered:true,durationThreshold:16}as any)}catch{}}});
for(const r of routes){const url=base+(r==='home'?'/':`/${r}/`);try{await page.goto(url,{waitUntil:'domcontentloaded',timeout:25000});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(700);if(r!=='home'){await page.locator('.menu-toggle').click();await page.locator('.menu-close').click()}const metrics=await page.evaluate(()=>({...((window as any).__lab),overflow:document.documentElement.scrollWidth>innerWidth+1,bytes:performance.getEntriesByType('resource').reduce((n:any,e:any)=>n+e.transferSize,0),h1:getComputedStyle(document.querySelector('h1')!).fontFamily}));report.lab.push({route:r,viewport:'390x844',cpu:4,...metrics,lcpPass:metrics.lcp>0&&metrics.lcp<=2500,clsPass:metrics.cls<=.1,maxInteractionProxy:Math.max(0,...metrics.events.map((e:any)=>e.duration))});}catch(e){report.lab.push({route:r,error:String(e)})}save()}
await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});
// Media filters: exact category counts, loading and controlled failure.
await page.goto(base+'/subsplash-media/#topics');await page.waitForSelector('.catalog-selectors:not([hidden])');const catalog=JSON.parse(fs.readFileSync('assets/data/media-browser.json','utf8'));for(const kind of ['topic','speaker','scripture']){await page.locator(`[data-kind=${kind}]`).selectOption('0');const count=catalog.categories[kind][0].item_ids.length;const cards=await page.locator('.catalog-item').count();report.interactions.push({test:'verified-category-'+kind,expected:Math.min(count,12),actual:cards,pass:cards===Math.min(count,12)})}await page.route('**/media-browser.json',r=>r.abort());await page.reload();await page.waitForTimeout(400);report.interactions.push({test:'catalog-failure-fallback',pass:(await page.locator('.catalog-status').innerText()).includes('unavailable')&&await page.locator('.library-fallback a').isVisible()});await page.unroute('**/media-browser.json');
// Real pin release on desktop-to-phone orientation, then reverse sequence.
await page.setViewportSize({width:1440,height:900});await page.goto(base+'/our-story/?motion-inspect=1');await page.waitForFunction(()=>!!(window as any).__motionInspector);await page.evaluate(()=>(window as any).__motionInspector.ready());const order=[];for(const n of [0,.45,.9,.45,0]){await page.evaluate(n=>(window as any).__motionInspector.seekScene('story-paired-chapters',n),n);order.push(await page.locator('.story-chapter.is-current .eyebrow').innerText())}await page.setViewportSize({width:844,height:390});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);report.interactions.push({test:'story-orientation-pin-release',pass:!await page.locator('.story-page').evaluate(e=>e.classList.contains('motion-ready')),sequence:order});
await page.goto(base+'/new/#visit-plan');await page.waitForTimeout(200);const anchor=await page.locator('#visit-plan').evaluate(e=>e.getBoundingClientRect().top);report.interactions.push({test:'direct-anchor-visible',top:anchor,pass:anchor>=0&&anchor<844});await page.goto(base+'/kids/');await page.goBack();report.interactions.push({test:'back-restores-route-anchor',pass:page.url().includes('/new/#visit-plan')});save();
await Promise.race([context.close(),new Promise(r=>setTimeout(r,3000))]);
const no=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const np=await no.newPage();for(const r of routes){try{await np.goto(base+(r==='home'?'/':`/${r}/`),{waitUntil:'domcontentloaded',timeout:15000});const d=await np.evaluate(()=>({h1:document.querySelector('h1')?.textContent,words:document.body.innerText.split(/\s+/).length,overflow:document.documentElement.scrollWidth>innerWidth+1,hidden:[...document.querySelectorAll('main p,main h1,main h2,main a')].filter(e=>getComputedStyle(e).opacity==='0').map(e=>e.textContent?.slice(0,40))}));report.nojs.push({route:r,...d,pass:!!d.h1&&d.words>20&&!d.overflow&&!d.hidden.length})}catch(e){report.nojs.push({route:r,error:String(e)})}save()}await Promise.race([browser.close(),new Promise(r=>setTimeout(r,3000))]);
try{const w=await webkit.launch({executablePath:'/Users/bobby/Library/Caches/ms-playwright/webkit-2336/pw_run.sh'});const wc=await w.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const wp=await wc.newPage();for(const r of ['home','our-story','mission','subsplash-media','404']){try{await wp.goto(base+(r==='home'?'/':`/${r}/`),{waitUntil:'domcontentloaded',timeout:20000});await wp.waitForTimeout(500);const d=await wp.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,h1:document.querySelector('h1')?.textContent,scrollHeight:document.documentElement.scrollHeight}));await wp.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await wp.waitForTimeout(100);report.webkit.push({route:r,...d,scrolled:await wp.evaluate(()=>scrollY),pass:!d.overflow&&!!d.h1})}catch(e){report.webkit.push({route:r,error:String(e)})}save()}await Promise.race([w.close(),new Promise(r=>setTimeout(r,3000))])}catch(e){report.webkit.push({status:'Unavailable',reason:String(e)});save()}console.log('resilience complete');process.exit(0);
