import {captureSite} from './capture.ts';
import {chromium} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('art-direction/references');const rows=JSON.parse(fs.readFileSync(root+'/pool-discovery.json','utf8'));
const choices={royal:['/about','/contact'],lou:['/about','/projects/vogue-america'],slab:['/projects/hydra','/archive'],consultpro:['/contact-us'],drospecta:['/pricing','/blog'],'net-folio':['/about','/work/sips-of-style'],nouva:['/contact','/sign-in'],'mvn-studio':['/contact','/legal-pages/privacy-policy'],agents:['/about','/work/echoes-copy'],atoks:['/about','/features'],outreach:['/pricing','/changelog'],fragments:[],portfoliod:[],'design-co':['/projects','/projects/lumé-studio'],blissful:['/about-me','/portfolio/anna-and-mark'],presenta:['/mailforge','/contact'],arix:['/about-us','/projects/vantage-spire'],perform:['/contact'],brightedge:['/about','/contact'],nexflow:['/contact','/pricing'],rivelle:['/about','/contact']};
const priority=['royal','lou','slab','rivelle'];rows.sort((a,b)=>(priority.includes(a.slug)?priority.indexOf(a.slug):-1+100)-(priority.includes(b.slug)?priority.indexOf(b.slug):-1+100));
const jobs=[];for(const row of rows){if(!row.home)continue;jobs.push({slug:row.slug,kind:'home',url:row.home});let picked=[];for(const p of choices[row.slug]||[]){const r=row.routes.find(r=>decodeURI(new URL(r.href).pathname)===p);if(r)picked.push(r)}if(picked.length<2&&!['fragments','portfoliod','consultpro','perform'].includes(row.slug)){for(const r of row.routes.filter(r=>!/404|legal|privacy|terms|style-guide/.test(r.href))){if(!picked.some(p=>p.href===r.href))picked.push(r);if(picked.length>=2)break}}for(const r of picked.slice(0,2))jobs.push({slug:row.slug,kind:new URL(r.href).pathname.replace(/^\//,'').replaceAll('/','-'),url:r.href});row.screenRoutes=picked.slice(0,2).map(r=>r.href)}fs.writeFileSync(root+'/screen-manifest.json',JSON.stringify({rows,jobs},null,2));
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const results=[];let index=0;async function worker(){while(index<jobs.length){const job=jobs[index++],outDir=path.join(root,'pool',job.slug,job.kind);try{const manifest=await captureSite({url:job.url,outDir,mode:'screen',viewports:['desktop','phone'],settleMs:900,browser});results.push({...job,outDir,status:manifest.status});console.log('CAPTURED',job.slug,job.kind,manifest.status)}catch(error){results.push({...job,error:String(error)});console.log('ERROR',job.slug,job.kind,String(error).slice(0,150))}fs.writeFileSync(root+'/screen-progress.json',JSON.stringify(results,null,2));}}
await Promise.all([worker(),worker(),worker()]);await browser.close();
