/** Selection is explicit editorial evidence, not an automated declaration of 'best'. */
import fs from 'node:fs/promises';import path from 'node:path';import{pathToFileURL}from'node:url';import{contactSheet}from'./compare.ts';
async function resolveState(item,viewport){const m=typeof item.manifest==='string'?JSON.parse(await fs.readFile(item.manifest,'utf8')):item.manifest;const state=m.viewports?.[viewport]?.states.find(s=>s.id===item.state);if(!state)throw Error(`Missing ${viewport} state ${item.state} in ${item.manifest}`);return{file:state.file,label:item.label||`${m.url} ${state.id}`,manifest:item.manifest,state:item.state,settled:state.settled};}
export async function generateTopExamples(selection,outDir){await fs.mkdir(outDir,{recursive:true});const results=[];for(const board of selection.boards){try{if(board.examples?.length!==3)throw Error('Exactly three observed selected examples required');const examples=await Promise.all(board.examples.map(e=>resolveState(e,board.viewport)));const build=await resolveState(board.build,board.viewport);const file=path.join(outDir,`${board.route}-${board.viewport}-${board.section||'opening'}.png`);await contactSheet({images:[examples[0],build,examples[1],examples[2]],out:file,width:board.viewport==='phone'?390:480,columns:4});results.push({...board,file:path.resolve(file),status:'Unreviewed',settled:[examples[0].settled,build.settled,examples[1].settled,examples[2].settled]})}catch(error){results.push({...board,status:'Missing-evidence',error:String(error)})}}await fs.writeFile(path.join(outDir,'index.json'),JSON.stringify({created:new Date().toISOString(),results},null,2));return results}
export async function selectionFromQueue(queuePath){
 const queue=JSON.parse(await fs.readFile(queuePath,'utf8'));const R='art-direction/references/deep/royal/about/manifest.json',P='art-direction/references/deep/royal/properties/manifest.json',C='art-direction/references/deep/royal/contact/manifest.json',L='art-direction/references/deep/lou-pilot/about/manifest.json',S='art-direction/references/deep/slab/hydra-scoped/manifest.json';const practical=new Set(['prayer','pastoral-care','weather-procedures','give','calendar','legal','404','watch-live','app']);const archive=new Set(['previous-messages','subsplash-media','courses','easter']);const boards=[];
 for(const[route,result]of Object.entries(queue.routes)){if(!result.manifest||result.status!=='Captured')continue;for(const viewport of ['desktop','tablet','phone']){const examples=practical.has(route)?[{manifest:C,state:'opening-settled',label:'Royal contact — immediate task hierarchy'},{manifest:S,state:'forward-002',label:'Slab brief — label and bounded explanation'},{manifest:L,state:'footer',label:'Lou contact — clear channels and calm space'}]:archive.has(route)?[{manifest:S,state:'opening',label:'Slab project — image then metadata'},{manifest:P,state:'opening-settled',label:'Royal index — featured item before collection'},{manifest:R,state:'section-team',label:'Royal people — consistent labeled imagery'}]:[{manifest:R,state:'opening-settled',label:'Royal story — real image and factual hierarchy'},{manifest:L,state:'opening-settled',label:'Lou portrait — decisive scale contrast'},{manifest:P,state:'opening-settled',label:'Royal index — image-led destination'}];boards.push({route,viewport,page_type:practical.has(route)?'practical':archive.has(route)?'archive':'narrative',section:'opening',build:{manifest:result.manifest,state:'opening-settled',label:route+' — current build'},examples,selection_reason:'Three observed comparisons selected for this visitor task. Comparative quality must be judged visually; selection itself is not a pass.'})}}
 // Include each authored section with its exact observed source as first comparator.
 const openings=[...boards];for(const b of openings){try{const bp=JSON.parse(await fs.readFile(`art-direction/pages/${b.route}/blueprint.json`,'utf8'));const m=JSON.parse(await fs.readFile(b.build.manifest,'utf8'));for(const section of bp.sections||[]){const state=`section-${section.id}`;if(!m.viewports[b.viewport].states.some(s=>s.id===state))continue;const ref=section.reference_section;if(!ref?.dossier)continue;const exact={manifest:ref.manifest||path.join(path.dirname(ref.dossier),'manifest.json'),state:ref.states?.[b.viewport]||ref.state||`section-${ref.landmark}`,label:'Assigned source — '+section.id};const hasExact=!!(ref.state||ref.landmark);const examples=hasExact?[exact,...b.examples.filter(e=>e.manifest!==exact.manifest||e.state!==exact.state)].slice(0,3):b.examples;if(examples.length===3)boards.push({...b,section:section.id,build:{...b.build,state},examples,selection_reason:hasExact?'Assigned section source plus two observed alternatives for comparison; not a claim that all are approved matches.':'No verified section equivalence. Three observed alternatives shown as comparison candidates only; route fidelity record remains Blocked.'});}}catch{}}
 return{created:new Date().toISOString(),boards};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){const args={};for(let i=2;i<process.argv.length;i+=2)args[process.argv[i].replace(/^--/,'')]=process.argv[i+1];if(args['from-queue']){const selection=await selectionFromQueue(args['from-queue']);await fs.mkdir(args.out,{recursive:true});await fs.writeFile(path.join(args.out,'selection.json'),JSON.stringify(selection,null,2));console.log(await generateTopExamples(selection,args.out));}else{if(!args.selection||!args.out)throw Error('Usage: top-examples.ts --selection selection.json --out DIR');const r=await generateTopExamples(JSON.parse(await fs.readFile(args.selection,'utf8')),args.out);console.log(JSON.stringify({boards:r.length,missing:r.filter(x=>x.status==='Missing-evidence').length}))}}
