// Purpose-built media collection, not a page-body renderer. Source membership is exact.
const selectors=[...document.querySelectorAll<HTMLSelectElement>('[data-kind]')];
const results=document.querySelector<HTMLElement>('.catalog-results')!;
const status=document.querySelector<HTMLElement>('.catalog-status')!;
const more=document.querySelector<HTMLButtonElement>('.catalog-more')!;
let catalog:any,current:string[]=[],shown=0,label='';
function append(){const batch=current.slice(shown,shown+12);for(const id of batch){const item=catalog.items[id];if(!item)continue;const article=document.createElement('article');article.className='catalog-item';const link=document.createElement('a');link.href=item.provider_url;const img=document.createElement('img');img.src=item.artwork;img.alt='';img.width=800;img.height=450;img.loading='lazy';img.addEventListener('error',()=>img.remove(),{once:true});const h=document.createElement('h3');h.textContent=item.title;const p=document.createElement('p');const dt=new Date(item.date);p.textContent=[item.speaker,Number.isNaN(+dt)?null:dt.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'})].filter(Boolean).join(' · ');link.append(img,h);article.append(link,p);results.append(article)}shown+=batch.length;more.hidden=shown>=current.length;status.textContent=`${label} · ${current.length} ${current.length===1?'message':'messages'}`}
more.addEventListener('click',()=>{const n=results.children.length;append();(results.children[n]?.querySelector('a') as HTMLElement)?.focus({preventScroll:true})});
async function start(){try{const response=await fetch('../assets/data/media-browser.json');if(!response.ok)throw Error('catalog unavailable');catalog=await response.json();for(const select of selectors){for(const [i,group]of catalog.categories[select.dataset.kind!].entries()){const o=document.createElement('option');o.value=String(i);o.textContent=group.label;select.append(o)}select.addEventListener('change',()=>{if(select.value===''){current=[];results.replaceChildren();status.textContent='Choose a topic, speaker, or Scripture book.';more.hidden=true;return}for(const other of selectors)if(other!==select)other.value='';const group=catalog.categories[select.dataset.kind!][Number(select.value)];current=[...group.item_ids].sort((a,b)=>String(catalog.items[b]?.date).localeCompare(String(catalog.items[a]?.date)));label=group.label;shown=0;results.replaceChildren();append()})}document.querySelector<HTMLElement>('.catalog-selectors')!.hidden=false;status.textContent='Choose a topic, speaker, or Scripture book.';if(['#topics','#speakers','#scripture'].includes(location.hash)){document.querySelector(location.hash)?.scrollIntoView({behavior:'instant'});document.querySelector<HTMLSelectElement>(`${location.hash} select`)?.focus({preventScroll:true})}}catch{status.textContent='The collection is temporarily unavailable. Open the full message library below.'}}
start();

// Owner-requested inner-page scroll responses; essential controls remain still.
import {scrollDetail} from "../scroll-detail.js";
scrollDetail({"id": "media-photo", "selector": ".media-opening figure", "kind": "image", "distance": 44});
scrollDetail({"id": "media-library", "selector": ".library-heading h2, .library-reading-column > p:first-child", "kind": "rise", "distance": 24, "stagger": 0.12});
